CREATE TABLE IF NOT EXISTS public.parcels (
  id                 BIGSERIAL PRIMARY KEY,
  object_id          INTEGER UNIQUE NOT NULL,
  year_val           INTEGER,
  name               TEXT,
  rayon              TEXT,
  sahe               DOUBLE PRECISION,
  kod                TEXT,
  olcutarix          DATE,
  ad                 TEXT,
  ok                 INTEGER,
  fayl               TEXT,
  importad           TEXT,
  importdt           TIMESTAMPTZ,
  ediad              TEXT,
  edidtt             TIMESTAMPTZ,
  okad               TEXT,
  okdt               TIMESTAMPTZ,
  olcen              TEXT,
  qeyd               TEXT,
  agronom_name       TEXT,
  village_name       TEXT,
  village_elder_name TEXT,
  district_name      TEXT,
  fin_kod            TEXT,
  village            TEXT,
  district           TEXT,
  id_value           TEXT,
  square             DOUBLE PRECISION,
  mulk               TEXT,
  teyinat            TEXT,
  itf                TEXT,
  il                 TEXT,
  geom               TEXT
);

CREATE TABLE IF NOT EXISTS public.sentinelresults (
  ad         VARCHAR(60),
  rayon      VARCHAR(60),
  object_id  INTEGER,
  ndvi       NUMERIC,
  ndwi       NUMERIC,
  evi        NUMERIC,
  img_date   DATE,
  FOREIGN KEY (object_id) REFERENCES public.parcels(object_id) ON DELETE CASCADE   ON UPDATE CASCADE
);